// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_rsTnxlW9w6GZBhdQRCV0fEa3W622xZs',
    appId: '1:394723530137:android:9eaaac953c7b02d3516f08',
    messagingSenderId: '394723530137',
    projectId: 'get-barber-online',
    storageBucket: 'get-barber-online.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0tuTDiPtCPIruu92Lyisg4JxIo9kjBis',
    appId: '1:394723530137:ios:6921520174773c71516f08',
    messagingSenderId: '394723530137',
    projectId: 'get-barber-online',
    storageBucket: 'get-barber-online.firebasestorage.app',
    iosBundleId: 'com.example.onlineBarberApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWkJxBAhOtf7gB_0520gjHTgS9jxf5jek',
    appId: '1:394723530137:web:93d9e17f2cf7e164516f08',
    messagingSenderId: '394723530137',
    projectId: 'get-barber-online',
    authDomain: 'get-barber-online.firebaseapp.com',
    storageBucket: 'get-barber-online.firebasestorage.app',
    measurementId: 'G-5KRTHGNCT8',
  );

}