// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQrH3CoXmbSVl4sKQqroQzwsldjvHiFGk',
    appId: '1:980382807544:android:9bedc09e4f680a1fae920d',
    messagingSenderId: '980382807544',
    projectId: 'online-barber-641ba',
    storageBucket: 'online-barber-641ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnLlsnoQ12njaAF349_jLGn68SFP3vwOk',
    appId: '1:980382807544:ios:e291bf6fac1f053fae920d',
    messagingSenderId: '980382807544',
    projectId: 'online-barber-641ba',
    storageBucket: 'online-barber-641ba.appspot.com',
    androidClientId: '980382807544-gb7n64bd0483pmpla3udjkd5dl40t6ba.apps.googleusercontent.com',
    iosClientId: '980382807544-2e8gp0berf08frnv5441vcdg1fk5on8a.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineBarberApp',
  );
}
